### ISSUE TITLE
Inline styles and scripts, incompatible with Content Security Policy

### ISSUE THREAD

**Issue by FrDH** [solspace/craft3-freeform#1341]
### What happened?

Due to a strict Content Security Policy that doesn't allow inline styles or inline scripts to be used, two honeypot fields are now visible and the JS isn't working. 

Even if I hide the fields manually in my stylesheet, there still will be an error in the console:
> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' 

I think all errors are caused by the "honeypot" and "javascript test" integrations. Is there a way to use them without using inline styles or inline scripts? 

### How can we reproduce this?

1. Set the content security policy in .htaccess to something like this: `Header set Content-Security-Policy "default-src 'self'; style-src 'self'; script-src 'self';"`
2. Add a honeypot to a form.
3. View the form on the frontend.

### Freeform Edition

Pro

### Freeform Version

5.3.1

### Craft Version

4.9.5

**Comment by kjmartens** [comment]
Sorry about this @FrDH,

We will move these scripts to no longer be inline. 🙂

**Comment by FrDH** [comment]
That would be awesome 👍

**Comment by FrDH** [comment]
I just noticed two more console logs about not being able to apply inline styles from within freeform.js. As this is a minified file I doubt this is very helpfull, but here are the two lines:
```
e.appendChild(document.createTextNode(t))
```
and
```
n.appendChild(r)
```
Hope this helps.

**Comment by gustavs-gutmanis** [comment]
Hi @FrDH,

Is it possible to pinpoint the exact script where it happens? Even a minified version would help. I have a feeling that these might be for google tag manager, or the like.

**Comment by FrDH** [comment]
It highlights the 2 lines that use `appendChild`. Hope that helps.
```
       6793: function(t) {
            "use strict";
            var e = {};
            t.exports = function(t, r) {
                var n = function(t) {
                    if (void 0 === e[t]) {
                        var r = document.querySelector(t);
                        if (window.HTMLIFrameElement && r instanceof window.HTMLIFrameElement)
                            try {
                                r = r.contentDocument.head
                            } catch (t) {
                                r = null
                            }
                        e[t] = r
                    }
                    return e[t]
                }(t);
                if (!n)
                    throw new Error("Couldn't find a style target. This probably means that the value for the 'insert' parameter is invalid.");

// IT's THIS LINE 
                n.appendChild(r)  
            }
        },

 ...

      2464: function(t) {
            "use strict";
            t.exports = function(t, e) {
                if (e.styleSheet)
                    e.styleSheet.cssText = t;
                else {
                    for (; e.firstChild; )
                        e.removeChild(e.firstChild);

// AND THIS LINE
                    e.appendChild(document.createTextNode(t)) 
                }
            }
        },

```

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.4. 🙂

**Comment by FrDH** [comment]
Thanks for the quick response.
I updated to 5.4 but am still getting some errors about inline styles.

```
<div id="..." data-scroll-anchor style="display: none;"></div>
<div class="..." style="position: absolute !important; width: 0 !important; height: 0 !important; overflow: hidden !important;" aria-hidden="true" tabindex="-1">
<div class="..." style="position: absolute !important; width: 0 !important; height: 0 !important; overflow: hidden !important;" aria-hidden="true" tabindex="-1">
<div data-rules-json="{...}" style="display: none;"></div>
```

The 2nd and 3rd are for respectively the honeypot and javascript spam protection. 

Also the two errors in freeform.js keep popping up (see screenshots).
![Scherm­afbeelding 2024-06-19 om 13 13 35](https://github.com/solspace/craft-freeform/assets/1387163/0a4ed51a-da85-40c6-9e4e-e8221ad3c3e3)

![Scherm­afbeelding 2024-06-19 om 13 13 47](https://github.com/solspace/craft-freeform/assets/1387163/a314e9a4-c213-4916-ae1d-3a3aadcd5069)

**Comment by kjmartens** [comment]
Sorry about this @FrDH. We'll have another go at it 🙂

**Comment by kjmartens** [comment]
Hi @FrDH,

We've accounted for the remaining unnecessary inline `style` attribute cases in 5.4.2. However, the `appendChild` issues you mention have to do with displaying errors for files in the File Drag & Drop field. We will need to check into alternate options for a suitable replacement.

**Comment by FrDH** [comment]
It looks like the `appendChild` error isn't interfering with the rest of the script, so for now we can have a working form (as long as we don't use the File Drag & Drop field).
Thanks for the update.

**Comment by kjmartens** [comment]
Thank you @FrDH. We ended up finding a solution for the appendChild issue, so that will be resolved in the next version of Freeform. 🙂

**Comment by FrDH** [comment]
Thanks! There are no more errors showing up in the console 👍
