### ISSUE TITLE
Not null violation:  null value in column "dateCreated" of relation "freeform_rules_conditions" violates not-null constraint

### ISSUE THREAD

**Issue by tinusWCreators** [solspace/craft3-freeform#1577]
### What happened?

I try to add a radio, and in the rules i try to say. If one of the values, show certain fields. When adding rules I get an error.
Updated to latest version "solspace/craft-freeform": "5.6.5".

### Errors and Stack Trace (if available)

```shell
{
    "name": "Integrity constraint violation",
    "message": "SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"dateCreated\" of relation \"freeform_rules_conditions\" violates not-null constraint\nDETAIL:  Failing row contains (4, 1, 14, equals, Naam organisatie, naam abonnee en/of adres is gewijzigd, null, null, 0                                   ).\nThe SQL being executed was: INSERT INTO \"freeform_rules_conditions\" (\"ruleId\", \"fieldId\", \"operator\", \"value\") VALUES (1, 14, 'equals', 'Naam organisatie, naam abonnee en/of adres is gewijzigd') RETURNING \"id\"",
    "code": "23502",
    "exception": "yii\\db\\IntegrityException",
    "file": "/var/www/html/vendor/yiisoft/yii2/db/Schema.php",
    "line": 676,
    "trace": [
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
            "line": 1325,
            "function": "convertException",
            "class": "yii\\db\\Schema",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
            "line": 1186,
            "function": "internalExecute",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
            "line": 431,
            "function": "queryInternal",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/pgsql/Schema.php",
            "line": 646,
            "function": "queryOne",
            "class": "yii\\db\\Command",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php",
            "line": 604,
            "function": "insert",
            "class": "yii\\db\\pgsql\\Schema",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php",
            "line": 570,
            "function": "insertInternal",
            "class": "yii\\db\\ActiveRecord",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php",
            "line": 688,
            "function": "insert",
            "class": "yii\\db\\ActiveRecord",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Persistence/Rules/FieldRulesPersistence.php",
            "line": 91,
            "function": "save",
            "class": "yii\\db\\BaseActiveRecord",
            "type": "->"
        },
        {
            "function": "handleRuleSave",
            "class": "Solspace\\Freeform\\Bundles\\Persistence\\Rules\\FieldRulesPersistence",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Event.php",
            "line": 312,
            "function": "call_user_func"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Component.php",
            "line": 650,
            "function": "trigger",
            "class": "yii\\base\\Event",
            "type": "::"
        },
        {
            "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/api/FormsController.php",
            "line": 169,
            "function": "trigger",
            "class": "yii\\base\\Component",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php",
            "line": 30,
            "function": "post",
            "class": "Solspace\\Freeform\\controllers\\api\\FormsController",
            "type": "->"
        },
        {
            "function": "actionIndex",
            "class": "Solspace\\Freeform\\controllers\\BaseApiController",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/InlineAction.php",
            "line": 57,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Controller.php",
            "line": 178,
            "function": "runWithParams",
            "class": "yii\\base\\InlineAction",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php",
            "line": 15,
            "function": "runAction",
            "class": "yii\\base\\Controller",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Module.php",
            "line": 552,
            "function": "runAction",
            "class": "Solspace\\Freeform\\controllers\\BaseApiController",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
            "line": 350,
            "function": "runAction",
            "class": "yii\\base\\Module",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/web/Application.php",
            "line": 103,
            "function": "runAction",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
            "line": 318,
            "function": "handleRequest",
            "class": "yii\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/vendor/yiisoft/yii2/base/Application.php",
            "line": 384,
            "function": "handleRequest",
            "class": "craft\\web\\Application",
            "type": "->"
        },
        {
            "file": "/var/www/html/web/index.php",
            "line": 12,
            "function": "run",
            "class": "yii\\base\\Application",
            "type": "->"
        }
    ],
    "previous": {
        "exception": "PDOException",
        "message": "SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"dateCreated\" of relation \"freeform_rules_conditions\" violates not-null constraint\nDETAIL:  Failing row contains (4, 1, 14, equals, Naam organisatie, naam abonnee en/of adres is gewijzigd, null, null, 0                                   ).",
        "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
        "line": 1320,
        "trace": [
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
                "line": 1320,
                "function": "execute",
                "class": "PDOStatement",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
                "line": 1186,
                "function": "internalExecute",
                "class": "yii\\db\\Command",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/Command.php",
                "line": 431,
                "function": "queryInternal",
                "class": "yii\\db\\Command",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/pgsql/Schema.php",
                "line": 646,
                "function": "queryOne",
                "class": "yii\\db\\Command",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php",
                "line": 604,
                "function": "insert",
                "class": "yii\\db\\pgsql\\Schema",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php",
                "line": 570,
                "function": "insertInternal",
                "class": "yii\\db\\ActiveRecord",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php",
                "line": 688,
                "function": "insert",
                "class": "yii\\db\\ActiveRecord",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Persistence/Rules/FieldRulesPersistence.php",
                "line": 91,
                "function": "save",
                "class": "yii\\db\\BaseActiveRecord",
                "type": "->"
            },
            {
                "function": "handleRuleSave",
                "class": "Solspace\\Freeform\\Bundles\\Persistence\\Rules\\FieldRulesPersistence",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/base/Event.php",
                "line": 312,
                "function": "call_user_func"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/base/Component.php",
                "line": 650,
                "function": "trigger",
                "class": "yii\\base\\Event",
                "type": "::"
            },
            {
                "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/api/FormsController.php",
                "line": 169,
                "function": "trigger",
                "class": "yii\\base\\Component",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php",
                "line": 30,
                "function": "post",
                "class": "Solspace\\Freeform\\controllers\\api\\FormsController",
                "type": "->"
            },
            {
                "function": "actionIndex",
                "class": "Solspace\\Freeform\\controllers\\BaseApiController",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/base/InlineAction.php",
                "line": 57,
                "function": "call_user_func_array"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/base/Controller.php",
                "line": 178,
                "function": "runWithParams",
                "class": "yii\\base\\InlineAction",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php",
                "line": 15,
                "function": "runAction",
                "class": "yii\\base\\Controller",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/base/Module.php",
                "line": 552,
                "function": "runAction",
                "class": "Solspace\\Freeform\\controllers\\BaseApiController",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
                "line": 350,
                "function": "runAction",
                "class": "yii\\base\\Module",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/web/Application.php",
                "line": 103,
                "function": "runAction",
                "class": "craft\\web\\Application",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/craftcms/cms/src/web/Application.php",
                "line": 318,
                "function": "handleRequest",
                "class": "yii\\web\\Application",
                "type": "->"
            },
            {
                "file": "/var/www/html/vendor/yiisoft/yii2/base/Application.php",
                "line": 384,
                "function": "handleRequest",
                "class": "craft\\web\\Application",
                "type": "->"
            },
            {
                "file": "/var/www/html/web/index.php",
                "line": 12,
                "function": "run",
                "class": "yii\\base\\Application",
                "type": "->"
            }
        ]
    }
}
```

### How can we reproduce this?

1. create a test form
2. Add an radio with option 1 and option 2
3. Add an email field
4. Go to rules tab select email and say something like:
Show: Radios is equal to Option 1
5. Attempt to save the form

### Freeform Edition

Pro

### Freeform Version

5.6.5

### Craft Version

5.4.8

### When did this issue start?

Unsure

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @tinusWCreators, we will look into it.

It seems like for some reason Craft is not automatically adding `dateCreated` and `dateUpdated` and `uid` column values to a new record when it is being saved, which is weird, because it usually does so. It might have something to do with PGSQL in this case, we will try to reproduce this and get back to you.

**Comment by tinusWCreators** [comment]
Hi gustav,
Thanks for the response. Yes indeed, we are using PGSQL. Our ddev environment uses version 13.

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 5.6.7. 🙂

**Comment by pc-erin** [comment]
I think this is still happening. I did a dump and die after before the ->save() in `FieldRulesPersistence` and that code path didn't get hit. It looks like the same changes might need to be made for other Persistence classes as well.

Here's an [SO article](https://stackoverflow.com/questions/48983282/how-do-i-update-the-last-updated-column-default-set-to-current-timestamp) on possible better ways to deal with this behavior when using ActiveRecords.

We are also on postgres.

Here's the error:

```
2025-03-18 13:21:10 [web.ERROR] [yii\db\IntegrityException] PDOException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "dateCreated" of relation "freeform_rules_conditions" violates not-null constraint
DETAIL:  Failing row contains (12, 3, 54, equals, 1, null, null, 0                                   ). in /app/vendor/yiisoft/yii2/db/Command.php:1320
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1320): PDOStatement->execute()
#1 /app/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('INSERT INTO "fr...')
#2 /app/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal('fetch', NULL)
#3 /app/vendor/yiisoft/yii2/db/pgsql/Schema.php(646): yii\db\Command->queryOne()
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\pgsql\Schema->insert('{{%freeform_rul...', Array)
#5 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
#6 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(688): yii\db\ActiveRecord->insert(true, NULL)
#7 /app/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Persistence/Rules/NotificationRulesPersistence.php(91): yii\db\BaseActiveRecord->save()
#8 [internal function]: Solspace\Freeform\Bundles\Persistence\Rules\NotificationRulesPersistence->handleRuleSave(Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#9 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#10 /app/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('Solspace\\Freefo...', 'upsert-form', Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#11 /app/vendor/solspace/craft-freeform/packages/plugin/src/controllers/api/FormsController.php(166): yii\base\Component->trigger('upsert-form', Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#12 /app/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php(30): Solspace\Freeform\controllers\api\FormsController->post('5')
#13 [internal function]: Solspace\Freeform\controllers\BaseApiController->actionIndex('5')
#14 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /app/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php(15): yii\base\Controller->runAction('', Array)
#17 /app/vendor/yiisoft/yii2/base/Module.php(552): Solspace\Freeform\controllers\BaseApiController->runAction('', Array)
#18 /app/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('freeform/api/fo...', Array)
#19 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('freeform/api/fo...', Array)
#20 /app/vendor/craftcms/cms/src/web/Application.php(309): yii\web\Application->handleRequest(Object(craft\web\Request))
#21 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /app/web/index.php(12): yii\base\Application->run()
#23 {main}

Next yii\db\IntegrityException: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "dateCreated" of relation "freeform_rules_conditions" violates not-null constraint
DETAIL:  Failing row contains (12, 3, 54, equals, 1, null, null, 0                                   ).
The SQL being executed was: INSERT INTO "freeform_rules_conditions" ("ruleId", "fieldId", "operator", "value") VALUES (3, 54, 'equals', '1') RETURNING "id" in /app/vendor/yiisoft/yii2/db/Schema.php:676
Stack trace:
#0 /app/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO "fr...')
#1 /app/vendor/yiisoft/yii2/db/Command.php(1186): yii\db\Command->internalExecute('INSERT INTO "fr...')
#2 /app/vendor/yiisoft/yii2/db/Command.php(431): yii\db\Command->queryInternal('fetch', NULL)
#3 /app/vendor/yiisoft/yii2/db/pgsql/Schema.php(646): yii\db\Command->queryOne()
#4 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(604): yii\db\pgsql\Schema->insert('{{%freeform_rul...', Array)
#5 /app/vendor/yiisoft/yii2/db/ActiveRecord.php(570): yii\db\ActiveRecord->insertInternal(NULL)
#6 /app/vendor/yiisoft/yii2/db/BaseActiveRecord.php(688): yii\db\ActiveRecord->insert(true, NULL)
#7 /app/vendor/solspace/craft-freeform/packages/plugin/src/Bundles/Persistence/Rules/NotificationRulesPersistence.php(91): yii\db\BaseActiveRecord->save()
#8 [internal function]: Solspace\Freeform\Bundles\Persistence\Rules\NotificationRulesPersistence->handleRuleSave(Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#9 /app/vendor/yiisoft/yii2/base/Event.php(312): call_user_func(Array, Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#10 /app/vendor/yiisoft/yii2/base/Component.php(650): yii\base\Event::trigger('Solspace\\Freefo...', 'upsert-form', Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#11 /app/vendor/solspace/craft-freeform/packages/plugin/src/controllers/api/FormsController.php(166): yii\base\Component->trigger('upsert-form', Object(Solspace\Freeform\Events\Forms\PersistFormEvent))
#12 /app/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php(30): Solspace\Freeform\controllers\api\FormsController->post('5')
#13 [internal function]: Solspace\Freeform\controllers\BaseApiController->actionIndex('5')
#14 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /app/vendor/solspace/craft-freeform/packages/plugin/src/controllers/BaseApiController.php(15): yii\base\Controller->runAction('', Array)
#17 /app/vendor/yiisoft/yii2/base/Module.php(552): Solspace\Freeform\controllers\BaseApiController->runAction('', Array)
#18 /app/vendor/craftcms/cms/src/web/Application.php(341): yii\base\Module->runAction('freeform/api/fo...', Array)
#19 /app/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('freeform/api/fo...', Array)
#20 /app/vendor/craftcms/cms/src/web/Application.php(309): yii\web\Application->handleRequest(Object(craft\web\Request))
#21 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#22 /app/web/index.php(12): yii\base\Application->run()
#23 {main}
Additional Information:
Array
(
    [0] => 23502
    [1] => 7
    [2] => ERROR:  null value in column "dateCreated" of relation "freeform_rules_conditions" violates not-null constraint
DETAIL:  Failing row contains (12, 3, 54, equals, 1, null, null, 0                                   ).
)
 {"memory":54377152,"exception":"[object] (yii\\db\\IntegrityException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"dateCreated\" of relation \"freeform_rules_conditions\" violates not-null constraint
DETAIL:  Failing row contains (12, 3, 54, equals, 1, null, null, 0                                   ).
The SQL being executed was: INSERT INTO \"freeform_rules_conditions\" (\"ruleId\", \"fieldId\", \"operator\", \"value\") VALUES (3, 54, 'equals', '1') RETURNING \"id\" at /app/vendor/yiisoft/yii2/db/Schema.php:676)
[previous exception] [object] (PDOException(code: 23502): SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column \"dateCreated\" of relation \"freeform_rules_conditions\" violates not-null constraint
DETAIL:  Failing row contains (12, 3, 54, equals, 1, null, null, 0                                   ). at /app/vendor/yiisoft/yii2/db/Command.php:1320)"} 
2025-03-18 13:21:10 [web.INFO] [application] Request context:
$_GET = [
    'p' => '/admin/freeform/api/forms/5'
]

{"environment":"dev","userId":2,"sessionId":"f2b47f5592fd3d21417e057cdc61dfc6","body":"{\"form\":{\"id\":5,\"uid\":\"a3de66be-fb55-4ad4-a8fe-57efd9b39b48\",\"type\":\"Solspace\\\\Freeform\\\\Form\\\\Types\\\\Regular\",\"settings\":{\"behavior\":{\"successMessage\":\"Form has been submitted successfully!\",\"errorMessage\":\"Sorry, there was an error submitting the form. Please try again.\",\"ajax\":true,\"showProcessingSpinner\":true,\"showProcessingText\":true,\"processingText\":\"Processing...\",\"successBehavior\":\"reload\",\"successTemplate\":null,\"returnUrl\":\"\",\"duplicateCheck\":\"no_limit\",\"stopSubmissionsAfter\":null},\"general\":{\"name\":\"Story Submission\",\"handle\":\"storySubmission\",\"type\":\"Solspace\\\\Freeform\\\\Form\\\\Types\\\\Regular\",\"sites\":[\"1\"],\"translations\":false,\"submissionTitle\":\"{{ dateCreated|date(\\\"Y-m-d H:i:s\\\") }}\",\"formattingTemplate\":\"grid\\/index.twig\",\"description\":\"\",\"color\":\"#ED3F1E\",\"attributes\":{\"form\":[],\"row\":[],\"success\":[],\"errors\":[]},\"storeData\":true,\"defaultStatus\":2,\"collectIpAddresses\":true,\"allowUsersToOptIn\":false,\"optInCheckbox\":null}}},\"integrations\":[{\"id\":1,\"enabled\":false,\"values\":[]},{\"id\":2,\"enabled\":true,\"values\":[]},{\"id\":3,\"enabled\":true,\"values\":[]}],\"layout\":{\"pages\":[{\"uid\":\"147e62ef-7981-4514-97cf-8d0a5c7e41a2\",\"label\":\"Page 1\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":0,\"buttons\":{\"layout\":\"back|submit save\",\"attributes\":{\"container\":[],\"column\":[],\"submit\":{\"class\":\"ow-button\"},\"back\":[],\"save\":[]},\"submitLabel\":\"Submit\",\"back\":true,\"backLabel\":\"Back\",\"save\":false,\"saveLabel\":\"Save\"}}],\"layouts\":[{\"uid\":\"48735aa5-f746-4dc9-80f6-362b66546719\"}],\"rows\":[{\"uid\":\"9365e09f-e89d-4369-9689-c82e1fec5895\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":0},{\"uid\":\"4849662a-73e7-4074-9db2-9eaf9bd62f2d\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":1},{\"uid\":\"6d909cf9-1ba9-462f-b5f1-ccd15db42430\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":2},{\"uid\":\"198fbaf3-8c9c-4855-92ac-7afa1479a802\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":3},{\"uid\":\"b98d2b66-f156-433d-a266-24b7cbf55c4a\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":4},{\"uid\":\"e33ff21e-a321-4787-bd4d-26690ec25b3a\",\"layoutUid\":\"48735aa5-f746-4dc9-80f6-362b66546719\",\"order\":5}],\"fields\":[{\"id\":51,\"uid\":\"6a00bcbe-6542-4254-8f96-8685be7763fc\",\"label\":\"What Town Do You Live In?\",\"rowUid\":\"6d909cf9-1ba9-462f-b5f1-ccd15db42430\",\"order\":0,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\TextField\",\"properties\":{\"label\":\"What Town Do You Live In?\",\"encrypted\":false,\"handle\":\"whatTownDoYouLiveIn\",\"fieldType\":null,\"instructions\":\"\",\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"placeholder\":\"Pullman, WA\",\"required\":false,\"requiredMessage\":null,\"defaultValue\":null,\"maxLength\":null}},{\"id\":49,\"uid\":\"106b2643-913d-433f-8d46-703c0ca1fe3e\",\"label\":\"Email\",\"rowUid\":\"4849662a-73e7-4074-9db2-9eaf9bd62f2d\",\"order\":0,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\EmailField\",\"properties\":{\"label\":\"Email\",\"encrypted\":false,\"handle\":\"email\",\"fieldType\":null,\"instructions\":\"\",\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"placeholder\":\"example@email.com\",\"required\":false,\"requiredMessage\":null,\"defaultValue\":null,\"maxLength\":null}},{\"id\":52,\"uid\":\"29768f11-5482-46ed-92e1-85164c3f65a8\",\"label\":\"Please accept all that you are comfortable sharing:\",\"rowUid\":\"198fbaf3-8c9c-4855-92ac-7afa1479a802\",\"order\":0,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\CheckboxesField\",\"properties\":{\"limit\":\"\",\"label\":\"Please accept all that you are comfortable sharing:\",\"encrypted\":false,\"limitMin\":null,\"handle\":\"checklist\",\"fieldType\":null,\"limitMax\":null,\"instructions\":\"\",\"limitRange\":null,\"defaultValue\":[],\"required\":true,\"requiredMessage\":null,\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"optionConfiguration\":{\"source\":\"custom\",\"useCustomValues\":false,\"options\":[{\"label\":\"Everything\",\"value\":\"Everything\"},{\"label\":\"My face\",\"value\":\"My face\"},{\"label\":\"My name\",\"value\":\"My name\"},{\"label\":\"My voice\",\"value\":\"My voice\"},{\"label\":\"The names of those mentioned\",\"value\":\"The names of those mentioned\"}]},\"oneLine\":true}},{\"id\":53,\"uid\":\"f5f6f459-ff3f-446e-a790-adfeaabc8b6d\",\"label\":\"File Upload\",\"rowUid\":\"b98d2b66-f156-433d-a266-24b7cbf55c4a\",\"order\":0,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\FileUploadField\",\"properties\":{\"fileCount\":1,\"label\":\"File Upload\",\"encrypted\":false,\"assetSourceId\":14,\"handle\":\"fileUpload\",\"fieldType\":null,\"defaultUploadLocation\":null,\"fileKinds\":[\"video\"],\"instructions\":\"(max file size: 2GB, format: mp4 or mov)\",\"maxFileSizeKB\":2000000,\"required\":true,\"requiredMessage\":null,\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]}}},{\"id\":54,\"uid\":\"5f3e7f7b-7d0d-48af-84c8-bfe0831895a9\",\"label\":\"Would you like information on SUD resources?\",\"rowUid\":\"e33ff21e-a321-4787-bd4d-26690ec25b3a\",\"order\":0,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\CheckboxField\",\"properties\":{\"label\":\"Would you like information on SUD resources?\",\"checkedByDefault\":false,\"handle\":\"checkbox\",\"fieldType\":null,\"instructions\":\"\",\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"required\":false,\"requiredMessage\":null,\"defaultValue\":null}},{\"id\":47,\"uid\":\"6fc1a443-65f8-4e7e-8eea-298ac85d17a7\",\"label\":\"First Name\",\"rowUid\":\"9365e09f-e89d-4369-9689-c82e1fec5895\",\"order\":0,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\TextField\",\"properties\":{\"label\":\"First Name\",\"encrypted\":false,\"handle\":\"firstName\",\"fieldType\":null,\"instructions\":\"\",\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"placeholder\":\"First Name\",\"required\":false,\"requiredMessage\":null,\"defaultValue\":null,\"maxLength\":null}},{\"id\":50,\"uid\":\"822d3c75-1a49-492c-8016-62c7a50a4721\",\"label\":\"Phone Number\",\"rowUid\":\"4849662a-73e7-4074-9db2-9eaf9bd62f2d\",\"order\":1,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\Pro\\\\PhoneField\",\"properties\":{\"pattern\":null,\"label\":\"Phone Number\",\"encrypted\":false,\"useJsMask\":false,\"handle\":\"phoneNumber\",\"fieldType\":null,\"instructions\":\"\",\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"placeholder\":\"(509) 867-5309\",\"required\":false,\"requiredMessage\":null,\"defaultValue\":null,\"maxLength\":null}},{\"id\":48,\"uid\":\"e2c7bb46-372f-44e7-ac49-5f4116e7f997\",\"label\":\"Last Name\",\"rowUid\":\"9365e09f-e89d-4369-9689-c82e1fec5895\",\"order\":1,\"typeClass\":\"Solspace\\\\Freeform\\\\Fields\\\\Implementations\\\\TextField\",\"properties\":{\"label\":\"Last Name\",\"encrypted\":false,\"handle\":\"lastName\",\"fieldType\":null,\"instructions\":\"\",\"attributes\":{\"input\":[],\"label\":[],\"instructions\":[],\"container\":[],\"error\":[],\"option\":[],\"optionLabel\":[]},\"placeholder\":\"Last Name\",\"required\":false,\"requiredMessage\":null,\"defaultValue\":null,\"maxLength\":null}}]},\"notifications\":[{\"template\":null,\"recipients\":[{\"email\":\"caitlin@propagandacreative.com\",\"name\":\"\"},{\"email\":\"phillipc@propagandacreative.com\",\"name\":\"\"}],\"id\":2,\"uid\":\"c1a53173-b330-4397-829d-c915622dcd4d\",\"enabled\":true,\"className\":\"Solspace\\\\Freeform\\\\Notifications\\\\Types\\\\Admin\\\\Admin\",\"name\":\"Admin notification 1\"},{\"template\":1,\"recipients\":[{\"email\":\"erin+test@propagandacreative.com\",\"name\":\"\"}],\"rule\":\"ced9cfaa-46a3-4472-ba81-63bd7d40eb37\",\"id\":3,\"uid\":\"00f43d0d-5bff-4489-a2c2-dc846ceedef6\",\"enabled\":true,\"className\":\"Solspace\\\\Freeform\\\\Notifications\\\\Types\\\\Conditional\\\\Conditional\",\"name\":\"Conditional notification 1\"}],\"rules\":{\"fields\":[],\"pages\":[],\"notifications\":[{\"uid\":\"ced9cfaa-46a3-4472-ba81-63bd7d40eb37\",\"enabled\":true,\"send\":true,\"combinator\":\"or\",\"notification\":\"00f43d0d-5bff-4489-a2c2-dc846ceedef6\",\"conditions\":[{\"uid\":\"e83330a7-b212-4485-8904-cf95f1d2b0d1\",\"field\":\"5f3e7f7b-7d0d-48af-84c8-bfe0831895a9\",\"operator\":\"equals\",\"value\":\"1\"}]}],\"submitForm\":null,\"buttons\":[]},\"translations\":null}"} 
```

**Comment by aaronrobb** [comment]
I'm seeing the same issue too on migration. 

```
Exception: SQLSTATE[23502]: Not null violation: 7 ERROR:  null value in column "dateCreated" of relation "freeform_rules_conditions" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 5, equals, Looking for a new home, null, null, 0  
```

Craft 5.7.1.1
Freeform 5.10.9
PostgreSQL 14.13

Did a pre-flight update to the latest 4.X version of everything first.
Then going from 4>5 i get that error on migration.
