### ISSUE TITLE
Freeform formatting template resources are not Craft Cloud compatible

### ISSUE THREAD

**Issue by timkelty** [solspace/craft3-freeform#1660]
### What happened?

Craft Cloud requires that front-end resources be [defined as asset bundles](https://craftcms.com/knowledge-base/cloud-plugin-development#asset-bundles), so it can publish them to the CDN at deploy time.

Freeform ships with Formatting Templates that attempt to load CSS/JS via `view.assetManager.publishedUrl`, but because those are never defined as Asset Bundles, they are never copied to the CDN: https://github.com/solspace/craft-freeform/blob/v5/packages/plugin/src/templates/_templates/formatting/flexbox/index.twig#L2-L3

The result is a URL to something like: https://cdn.craft.cloud/{envId}/builds/{buildId}/cpresources/Solspace-Freeform-templates-_templates-formatting-flexbox/_main.css which will be a 404.

The most straightforward way to address this would probably be to move the referenced assets to `packages/plugin/src/Resources/{css,js}` and a corresponding \Solspace\Freeform\Resources\Bundles\TemplateBundle`.

### How can we reproduce this?

Render a form using a formatting template that includes resources, eg `flexbox`.

### Freeform Edition

Pro

### Freeform Version

5.6.8

### Craft Version

5.4.9

**Comment by kjmartens** [comment]
Thank you for bringing this to our attention @timkelty.

We'll look into this and address it shortly. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 5.8 🙂

**Comment by timkelty** [comment]
I'm still getting reports of it not working on 5.8, with URLs 404ing like:
- https://cdn.craft.cloud/766280ce-df4b-4663-89dd-2b1a52511ec5/builds/9db36663-0967-4478-9292-1e48e26a1de4/cpresources/Solspace-Freeform-templates-_templates-formatting-flexbox/_main.js?v=1733812823
- https://cdn.craft.cloud/766280ce-df4b-4663-89dd-2b1a52511ec5/builds/9db36663-0967-4478-9292-1e48e26a1de4/cpresources/Solspace-Freeform-templates-_templates-formatting-flexbox/_main.css?v=1733812823

**Comment by kjmartens** [comment]
Sorry about this @timkelty. We'll look into it shortly.

**Comment by gustavs-gutmanis** [comment]
Hi @timkelty,

I moved all assets into their own Bundles and am loading the bundles within the templates in this commit: 05cddb8cc63e87009a76ea15ac04a89e5e21b40f

I'm not really sure what else to do here, could you give some guidance, please?

**Comment by timkelty** [comment]
@gustavs-gutmanis The conversion to asset bundles makes them publishable, which is great. What's happening now is an issue with alias resolution.

Asset bundle classes are instantiated and published in isolation, meaning the `@freeform-formatting-templates` alias defined `\Solspace\Freeform\Freeform::init` isn't available when the bundle is published.

The easiest fix is to always use the automatic alias the plugin installer adds for you based on your, in this case `@Solspace/Freeform`. Which would make these asset bundles' `sourcePath` look something like:

```php

// @freeform-formatting-templates is defined in \Solspace\Freeform\Freeform::init, which isn't called when `craft cloud/asset-bundles/publish` publishes asset bundles to the CDN
// $this->sourcePath = '@freeform-formatting-templates/flexbox';

// So, if we want to use an alias, we can use the automatically registered one:
$this->sourcePath = '@Solspace/Freeform/templates/_templates/formatting/flexbox';
```

**Comment by kjmartens** [comment]
This should be resolved in 5.8.3+ 🙂
