### ISSUE TITLE
Checkbox mapped to entry returns invalid when unchecked

### ISSUE THREAD

**Issue by samlising** [solspace/craft3-freeform#1877]
### What happened?

When submitting an Ajax form with a checkbox unchecked and the checkbox mapped to checkboxes in a craft entry, the submission will fail with an "invalid" error. 

Looking at the submitted data from freeform to craft, it looks like an unchecked checkbox value is "null". In Freeform 4 the value is "". I believe this is causing an "invalid" error from craft because it can not accept a null value. 

### Errors and Stack Trace (if available)

```shell

```

### How can we reproduce this?

1. map a checkbox in freeform to a checkbox in an entry
2. submit the form with the checkbox unchecked
3. Form will return an error saying the checkbox field is invalid

### Freeform Edition

Pro

### Freeform Version

5.9.16.1

### Craft Version

Craft Pro 4.14.8.1

### When did this issue start?

- [ ] Unsure
- [ ] Fresh install of Freeform
- [x] After upgrading from older Freeform version
- [ ] After upgrading from older Craft version
- [ ] After a change to hosting configuration

### Previous Freeform Version

4.1.24

**Comment by kjmartens** [comment]
Sorry about this @samlising,

I can duplicate this in my testing as well. We'll get it fixed shortly. 🙂

**Comment by samlising** [comment]
Thank you for your quick response. Really appreciate it.

**Comment by kjmartens** [comment]
No problem!

I should note that it will map to Craft Lightswitch fields. I can see why it's an issue with Craft Checkboxes because they're sort of intended to be multiple checkboxes, but can still have a single checkbox.

I'm sure we can just add a transformer for it so it plays nicely. 🙂

**Comment by samlising** [comment]
Unfortunately, I all the site forms with checkbox versus checkboxes fields and I can’t change them to checkboxes. It would make sense that I should have started with checkboxes but for some reason I didn’t :( 
I converting the existing checkbox field to checkboxes but I was getting javascript errors when trying to render the field. If there is a way to convert the fields to checkboxes - please let me know. 

I can’t convert the checkbox fields in craft to Lightswitches either. I believe I will loose existing data if I convert the fields. 

It would be great if you could make a fix for this and I can eventually add new checkboxes fields and import old submission data into the new fields. 

Thanks

**Comment by kjmartens** [comment]
No worries. We are working on a solution. 🙂

**Comment by kjmartens** [comment]
This fix is now fixed in Freeform 5.10.3+. 🙂

**Comment by samlising** [comment]
I've updated freeform to the latest version but I am still getting an invalid error when a form is submitted with a checkbox unchecked. 

I have output the values submitted from the "freeform-ajax-error" event and it still shows the submitted value as null when unchecked. Here is the output from event.response - the checkbox error is from the value "professional"

{
    "success": false,
    "finished": false,
    "onSuccess": "load-success-template",
    "id": null,
    "hash": "",
    "values": {
        "email": "x@y.com",
        "firstName": "x",
        "lastName": "y",
        "password": "1111111111",
        "confirmPassword": "1111111111",
        "organization": "",
        "professional": null,
        "subscribed": "Yes",
        "recaptchaTerms": null,
        "gdprConsent": "Yes",
        "languageHidden": "en",
    },
    "errors": [],
    "formErrors": [
        "Professional is invalid."
    ],
    "returnUrl": "/en/favorites",
    "submissionId": null,
    "actions": [],
    "multipage": false,
    "duplicate": false,
}

In Freeform 4 unchecked checkbox values were "" instead of null - I believe that is the problem. If I check the professional box the form submits without error. 

I have tried to resave the forms but I still get this error. Please let me know if there is something I need to do in order to make your update work. 

Thanks
Sam
