### ISSUE TITLE
Changing success behaviour of form from return url to reload still use the return url

### ISSUE THREAD

**Issue by RMAipassa** [solspace/craft3-freeform#2047]
### What happened?

Changed one of my forms success behaviour from return url to Reload Form with Success Message. And after i did this and submitted a form it still used the return url and send me to another page. 

I checked, and the return url field stays filled. And in the SubmitController there is no check for the successbehaviour for reload of return url, only for the load-success-template.

### Errors and Stack Trace (if available)

```shell

```

### How can we reproduce this?

1. Make a new form and set the success behaviour to return url
2. After saving this change the behaviour to Reload Form with Success Message
3. Submit a form with this setting and you should be send to the return url

### Freeform Edition

Pro

### Freeform Version

4.1.19

### Craft Version

4.14.15

### When did this issue start?

- [x] Unsure
- [ ] Fresh install of Freeform
- [ ] After upgrading from older Freeform version
- [ ] After upgrading from older Craft version
- [ ] After a change to hosting configuration

**Comment by kjmartens** [comment]
Sorry about this @RMAipassa,

Do you have AJAX enabled or disabled for this form? I can duplicate this issue if AJAX is disabled. I will have a developer check into this.

In the meantime, you can switch the success behavior to **Return URL**, delete the value, and change back to **Reload Form with Success Message**. Or, change the form use AJAX instead. 🙂

**Comment by kjmartens** [comment]
This should be resolved now in Freeform 4.1.27. 🙂

**Comment by RMAipassa** [comment]
@kjmartens So we have recently updated from 4.1.19 to 4.1.28 and the issue still persists. We did not have the Enable Ajax check on for the form itself, but we ourselves do sent the Ajax header. But it does not make a difference if its enabled or disabled for the form. Simply because of how the code works in the submitController:
```
$returnUrl = $formsService->getReturnUrl($form, $submission);

$form->reset();
$form->persistState();

if ($isAjaxRequest) {
    return $this->toAjaxResponse($form, $submission, $returnUrl);
}
```

Here you can see the returnUrl is added as a parameter if its an ajax request. So if the returnUrl field is still set, and you change the form to the reload on succes behaviour it will still go to the return url. 
The check that was added for the bug without ajax was this:
```
if (Form::SUCCESS_BEHAVIOUR_RELOAD === $form->getSuccessBehaviour()) {
    return null;
}
```
Shouldnt such a check also be made for when it is an ajax request or am i wrong about that?
