### ISSUE TITLE
Migration Error - 4.1.27 => 5.11.6

### ISSUE THREAD

**Issue by segidev** [solspace/craft3-freeform#2085]
### What happened?

I have tried upgrading from 4.1.27 to 5.0.0, then 5.0.1 and so and everywhere I have encountered issues with the migrations. Finally I went straight to the latest version and I still have an issue with the migration for a table that is created during the migrations from 5.0.0 on so it is not an error from my side having something in an existing table.

`52 from 61 migrations were applied.`

### Errors and Stack Trace (if available)

```shell
Applying new migrations ...

...

*** applying m250321_131543_AddFormIdToNotificationTemplates
    > add column formId integer to table {{%freeform_notification_templates}} ... done (time: 0.000s)
    > add foreign key fk_qlbrtxhbodhodrkaiaawcgtkrqiqgvuozcoo: {{%freeform_notification_templates}} (formId) references {{%freeform_forms}} (id) ... done (time: 0.001s)
    > execute SQL: ALTER TABLE {{%freeform_notification_templates}} DROP CONSTRAINT IF EXISTS freeform_notification_templates_handle_key ... done (time: 0.000s)
    > dropping index on {{%freeform_notification_templates}} if it exists ...Exception: SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop index freeform_notifications_handle_key because constraint freeform_notifications_handle_key on table freeform_notification_templates requires it
HINT:  You can drop constraint freeform_notifications_handle_key on table freeform_notification_templates instead.
The SQL being executed was: DROP INDEX "freeform_notifications_handle_key" (/var/www/html/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX "fre...')
#1 /var/www/html/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('DROP INDEX "fre...')
#2 /var/www/html/vendor/craftcms/cms/src/helpers/Db.php(1218): yii\db\Command->execute()
#3 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(354): craft\helpers\Db::dropIndexIfExists('{{%freeform_not...', 'handle', true, Object(craft\db\Connection))
#4 /var/www/html/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m250321_131543_AddFormIdToNotificationTemplates.php(34): craft\db\Migration->dropIndexIfExists('{{%freeform_not...', 'handle', true)
#5 /var/www/html/vendor/craftcms/cms/src/db/Migration.php(50): Solspace\Freeform\migrations\m250321_131543_AddFormIdToNotificationTemplates->safeUp()
#6 /var/www/html/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
#7 /var/www/html/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m250321_131543_...')
#8 [internal function]: craft\console\controllers\MigrateController->actionAll()
#9 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#10 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#11 /var/www/html/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#12 /var/www/html/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
#13 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
#14 /var/www/html/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#15 /var/www/html/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
#16 /var/www/html/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('migrate/all', Array)
#17 /var/www/html/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
#18 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#19 /var/www/html/craft(22): yii\base\Application->run()
#20 {main}
*** failed to apply m250321_131543_AddFormIdToNotificationTemplates (time: 0.012s)
```

### How can we reproduce this?

1. Set Freeform to 4.1.27
2. Run `ddev php craft update freeform`

### Freeform Edition

Pro

### Freeform Version

5.11.6

### Craft Version

Craft Pro 4.16.5

### When did this issue start?

- [ ] Unsure
- [ ] Fresh install of Freeform
- [x] After upgrading from older Freeform version
- [ ] After upgrading from older Craft version
- [ ] After a change to hosting configuration

### Previous Freeform Version

4.1.27

**Comment by boboldehampsink** [comment]
Also seeing this when upgrading from 5.11.5

```
web-1  |     > create unique index handle on {{%freeform_notification_template_wrappers}} (handle) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'handle'
web-1  | The SQL being executed was: ALTER TABLE `freeform_notification_template_wrappers` ADD UNIQUE INDEX `handle` (`handle`) (/app/user/vendor/yiisoft/yii2/db/Schema.php:676)
```

**Comment by kjmartens** [comment]
Sorry about this @segidev and @boboldehampsink,

We'll check into this issue shortly.

**Comment by kjmartens** [comment]
Are both of you able to provide a screenshot of your Freeform Diagnostics page, and possibly send us a copy of your database to support@solspace.com for review? 🙂

**Comment by segidev** [comment]
Sure I will send a screenshot

**Comment by boboldehampsink** [comment]
<img width="801" height="1160" alt="Image" src="https://github.com/user-attachments/assets/7314ff78-3087-44dd-b20b-86d7dd7471c9" />

Here is a screenshot. As for the database, I'm having issues on a clean install (with existing project config tho).

**Comment by kjmartens** [comment]
Hi @segidev,

This should be resolved in Freeform 5.11.7+ now. 🙂 

@boboldehampsink, I'm not sure if the issue you're experiencing is the same one as @segidev. When exactly are you getting these errors? And is it possible for you to provide a copy of DB anyway? I have tested this on a PostgreSQL install and I can't seem to duplicate it.

**Comment by segidev** [comment]
@kjmartens 
Thank you. I will try it and let you know asap

EDIT: I can confirm it works now, thank you 🙏

**Comment by boboldehampsink** [comment]
> Hi [@segidev](https://github.com/segidev),
> 
> This should be resolved in Freeform 5.11.7+ now. 🙂
> 
> [@boboldehampsink](https://github.com/boboldehampsink), I'm not sure if the issue you're experiencing is the same one as [@segidev](https://github.com/segidev). When exactly are you getting these errors? And is it possible for you to provide a copy of DB anyway? I have tested this on a PostgreSQL install and I can't seem to duplicate it.

This still happens on the new version. I spin up a version of my project (fresh db, project config in place) on 5.11.5, then upgrade to 5.11.6/7 and the migration throws this error:

```
web-1  | *** applying m250704_092101_ChangeWrapperNameIndexToHandle
web-1  |     > dropping index on {{%freeform_notification_template_wrappers}} if it exists ... done (time: 0.002s)
web-1  |     > create unique index handle on {{%freeform_notification_template_wrappers}} (handle) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'handle'
web-1  | The SQL being executed was: ALTER TABLE `freeform_notification_template_wrappers` ADD UNIQUE INDEX `handle` (`handle`) (/app/user/vendor/yiisoft/yii2/db/Schema.php:676)
web-1  | #0 /app/user/vendor/yiisoft/yii2/db/Command.php(1325): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `fr...')
web-1  | #1 /app/user/vendor/yiisoft/yii2/db/Command.php(1120): yii\db\Command->internalExecute('ALTER TABLE `fr...')
web-1  | #2 /app/user/vendor/yiisoft/yii2/db/Migration.php(506): yii\db\Command->execute()
web-1  | #3 /app/user/vendor/craftcms/cms/src/db/Migration.php(450): yii\db\Migration->createIndex('handle', '{{%freeform_not...', Array, true)
web-1  | #4 /app/user/vendor/solspace/craft-freeform/packages/plugin/src/migrations/m250704_092101_ChangeWrapperNameIndexToHandle.php(23): craft\db\Migration->createIndex('handle', '{{%freeform_not...', Array, true)
web-1  | #5 /app/user/vendor/craftcms/cms/src/db/Migration.php(50): Solspace\Freeform\migrations\m250704_092101_ChangeWrapperNameIndexToHandle->safeUp()
web-1  | #6 /app/user/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(758): craft\db\Migration->up()
web-1  | #7 /app/user/vendor/craftcms/cms/src/console/controllers/MigrateController.php(361): yii\console\controllers\BaseMigrateController->migrateUp('m250704_092101_...')
web-1  | #8 [internal function]: craft\console\controllers\MigrateController->actionAll()
web-1  | #9 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web-1  | #10 /app/user/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
web-1  | #11 /app/user/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
web-1  | #12 /app/user/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('all', Array)
web-1  | #13 /app/user/vendor/yiisoft/yii2/base/Module.php(552): craft\console\controllers\MigrateController->runAction('all', Array)
web-1  | #14 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
web-1  | #15 /app/user/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('migrate/all', Array)
web-1  | #16 /app/user/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
web-1  | #17 /app/user/vendor/craftcms/cms/src/console/Controller.php(207): yii\base\Controller->run('migrate/all', Array)
web-1  | #18 /app/user/vendor/craftcms/cms/src/console/controllers/UpController.php(64): craft\console\Controller->run('migrate/all', Array)
web-1  | #19 [internal function]: craft\console\controllers\UpController->actionIndex()
web-1  | #20 /app/user/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
web-1  | #21 /app/user/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
web-1  | #22 /app/user/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
web-1  | #23 /app/user/vendor/craftcms/cms/src/console/ControllerTrait.php(90): yii\console\Controller->runAction('', Array)
web-1  | #24 /app/user/vendor/craftcms/cms/src/console/Controller.php(216): craft\console\Controller->traitRunAction('', Array)
web-1  | #25 /app/user/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
web-1  | #26 /app/user/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
web-1  | #27 /app/user/vendor/craftcms/cms/src/console/Application.php(91): yii\console\Application->runAction('up', Array)
web-1  | #28 /app/user/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
web-1  | #29 /app/user/vendor/craftcms/cms/src/console/Application.php(122): yii\console\Application->handleRequest(Object(craft\console\Request))
web-1  | #30 /app/user/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
web-1  | #31 /app/user/craft(20): yii\base\Application->run()
web-1  | #32 {main}
web-1  | *** failed to apply m250704_092101_ChangeWrapperNameIndexToHandle (time: 0.003s)
```

I will send a dump of this db to your email

**Comment by gustavs-gutmanis** [comment]
Hi, @boboldehampsink 

Could you check the `freeform_notification_template_wrappers` table please, and see if there are any templates there with the same `handle`?

**Comment by boboldehampsink** [comment]
> Hi, [@boboldehampsink](https://github.com/boboldehampsink)
> 
> Could you check the `freeform_notification_template_wrappers` table please, and see if there are any templates there with the same `handle`?

Its empty

**Comment by gustavs-gutmanis** [comment]
Ok, then we'll take a look at the DB dump and try to figure out what's happening.

**Comment by boboldehampsink** [comment]
> Hi [@segidev](https://github.com/segidev),
> 
> This should be resolved in Freeform 5.11.7+ now. 🙂
> 
> [@boboldehampsink](https://github.com/boboldehampsink), I'm not sure if the issue you're experiencing is the same one as [@segidev](https://github.com/segidev). When exactly are you getting these errors? And is it possible for you to provide a copy of DB anyway? I have tested this on a PostgreSQL install and I can't seem to duplicate it.

Using MySQL for this installation btw
