### ISSUE TITLE
Submit buttons incorrectly disabled (aria-disabled="true") on all forms after 5.11.7 update

### ISSUE THREAD

**Issue by martinleveille** [solspace/craft3-freeform#2121]
## Bug Description
After upgrading to Freeform 5.11.7, all submit buttons across all forms are being rendered with `aria-disabled="true"` and `data-disabled="true"` attributes, making forms completely inaccessible and unusable.

## Expected Behavior
Submit buttons should only have disabled attributes when there's a valid reason (e.g., invalid file upload in progress).

## Actual Behavior
All submit buttons have `aria-disabled="true"` and `data-disabled="true"` attributes by default, preventing form submission and breaking accessibility.

## Additional Context
This appears to be related to the changelog entry for 5.11.7:
> "The form submit button is now locked when an invalid file type is added to a File Upload Drag & Drop field, and remains locked until the file is removed."

The issue affects all forms, including those without any file upload fields, suggesting the disabled state logic is being applied too broadly.

## Impact
This is a critical accessibility issue that renders all forms unusable for users relying on assistive technologies and prevents any form submissions.

### Errors and Stack Trace (if available)

```shell

```

### How can we reproduce this?

1. Upgrade Freeform to 5.11.7
2. Load any form (with or without file upload fields)
3. Inspect the submit button element

### Freeform Edition

Pro

### Freeform Version

5.11.7

### Craft Version

4.16.11

### When did this issue start?

- [ ] Unsure
- [ ] Fresh install of Freeform
- [x] After upgrading from older Freeform version
- [ ] After upgrading from older Craft version
- [ ] After a change to hosting configuration

### Previous Freeform Version

5.11.6

**Comment by kjmartens** [comment]
I can confirm this as well, @martinleveille.

We'll get it resolved shortly. 🙂

**Comment by kjmartens** [comment]
This should now be resolved in Freeform 5.11.12+ 🙂

**Comment by kerrig** [comment]
I just noticed this issue as well, I tried updating to 5.11.12 but I still see the issue happening, are you sure this was fixed in 5.11.12? It's preventing all forms from being submitted on my site.

**Comment by kjmartens** [comment]
Hi @kerrig,

It was resolved in my testing. However, I wonder if it is happening under certain scenarios. Could you share with me how you're loading the form and if you're using a custom formatting template, etc?

Can you also try this guide (starting at Step 2) to see what happens? 🙂 
https://docs.solspace.com/craft/freeform/v5/guides/guide/troubleshooting-form-issues/#create-a-new-simple-template

**Comment by kerrig** [comment]
@kjmartens I'm loading the form using the render function with passing in some variables from the CMS (including the form handle):
`{% if redirectUrl|length %}
    {{ craft.freeform.form(formHandle).render({
        fieldIdPrefix: "form-" ~ formIndex ~ "-",
        returnUrl: redirectUrl
    }) }}
{% else %}
    {{ craft.freeform.form(formHandle).render({
        fieldIdPrefix: "form-" ~ formIndex ~ "-"
    }) }}
{% endif %}`

I also use Blitz caching on the site so I'm setting the CSRF token via ajax using the [documentation method for Single & Multi-page forms](https://docs.solspace.com/craft/freeform/v5/templates/caching/#static-caching--blitz).

I tested setting up the simple template using the docs you sent and all worked as expected on the latest version. I then went through trying to add pieces to make it match my other templates and it seems once I add in global JS/styles (using Vite) is when it starts breaking. 
`{{ craft.vite.script("assets/js/main.js", false) }}`

This all works in version 5.11.6, but breaks in 5.11.7 and higher.

I'll also point out, when I test creating the simple template, I still do see the aria-disabled=true, but the submit button does function as expected:
`<button data-freeform-action="submit" data-button-container="submit" name="form_page_submit" type="submit" aria-disabled="true" data-disabled="true" data-original-text="Submit" data-processing-text="Processing...">Submit</button>`

Reverting to version 5.11.6, I don't see those values in the simple template test:
`<button data-freeform-action="submit" data-button-container="submit" name="form_page_submit" type="submit" data-original-text="Submit" data-processing-text="Processing...">Submit</button>`

**Comment by gustavs-gutmanis** [comment]
Hi @kerrig,

Sorry to hear you're still having issues with this.
Based on the description you've given here, it sounds like the scripts being loaded are of an older version.

- Could you please open up the working demo page, and get the contents of the loaded freeform.js as one file
- And then open the page where it's broken for you, and get the contents of that freeform.js

And send both of these to support@solspace.com?

Because the `aria-disabled` and `data-disabled` attributes not being removed is what we fixed, so they should not be lingering around.

**Comment by kerrig** [comment]
@gustavs-gutmanis  It actually looks like this is fixed in the latest version, 5.12.0. I was in the process of getting these scripts to provide to you and noticed when I updated to the latest it was no longer broken, it looks like it was broken 5.11.7 through 5.11.17. As it's fixed in the latest version, I assume you no longer need the scripts for debugging?

**Comment by gustavs-gutmanis** [comment]
Glad to hear it's working for you now. I don't need the files since that's the case :)
